## https://www.nltk.org/install.html
#### all instructions here

In [11]:
import nltk

# Download the specific resource mentioned in your error
nltk.download('punkt_tab')

# Since you'll need these for the next steps, download them now too
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Suraj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Suraj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Suraj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Suraj\AppData\Roaming\nltk_data...

True

In [1]:
import pandas as pd
import ast
import numpy as np

In [2]:
faq = pd.read_csv("faq_test_dataset.csv")
faq

,Question,Answer
0,How can I track my order?,You can track your order using the 'Track Orde...
1,What is your return policy?,We offer a 30-day return policy for most items...
2,How do I cancel my order?,You can cancel your order from the 'My Orders'...
3,Do you offer international shipping?,"Yes, we ship to over 50 countries. Shipping co..."
4,How can I contact customer support?,You can reach us via live chat on our website ...
5,What payment methods do you accept?,"We accept Visa, Mastercard, American Express, ..."
6,How do I reset my account password?,"Go to the login page, click 'Forgot Password',..."
7,Is there a warranty on electronic items?,All electronics come with a standard 1-year ma...
8,How long does delivery take?,Standard delivery typically takes 3-5 business...
9,Can I change my shipping address after placing...,Shipping addresses can only be changed within ...
10,Do you have a physical store I can visit?,We are an online-only store and do not have ph...
11,How do I apply a discount code?,You can enter your discount code in the 'Promo...
12,What should I do if my item arrived damaged?,Please take a photo of the damaged item and co...
13,Are there any membership or loyalty programs?,Yes! Our 'Rewards Club' allows you to earn poi...
14,How do I delete my account?,"To delete your account, please go to Account S..."

### Preprocessing Code

In [7]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

# Initialize the tools
lemmatizer = WordNetLemmatizer() #base for changer
stop_words = set(stopwords.words('english')) #stop words removal

def preprocess_text(text):
    # 1. Convert to lowercase
    text = text.lower()
    # print(text)
    
    # 2. Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # print(text)
    
    # 3. Tokenize (split into words)
    tokens = nltk.word_tokenize(text)
    print(tokens)
    
    # 4. Remove stopwords and Lemmatize
    clean_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    print(clean_tokens)
    
    return " ".join(clean_tokens)

# Test it out!
sample_q = "How can I apply for a scholarship?"
print(f"Original: {sample_q}")
print(f"Cleaned:  {preprocess_text(sample_q)}")

Original: How can I apply for a scholarship?
['how', 'can', 'i', 'apply', 'for', 'a', 'scholarship']
['apply', 'scholarship']
Cleaned:  apply scholarship

## Processing the whole dataset

#### Step 1: Loading and Cleaning the CSV

In [8]:
import pandas as pd

# 1. Load the dataset we created earlier
faq = pd.read_csv('faq_test_dataset.csv')

# 2. Create a new column 'Cleaned_Question' by applying our function
faq['Cleaned_Question'] = faq['Question'].apply(preprocess_text)

# 3. View the results to ensure it looks right
print("--- Processed Dataframe ---")
faq[['Question', 'Cleaned_Question']]
faq

['how', 'can', 'i', 'track', 'my', 'order']
['track', 'order']
['what', 'is', 'your', 'return', 'policy']
['return', 'policy']
['how', 'do', 'i', 'cancel', 'my', 'order']
['cancel', 'order']
['do', 'you', 'offer', 'international', 'shipping']
['offer', 'international', 'shipping']
['how', 'can', 'i', 'contact', 'customer', 'support']
['contact', 'customer', 'support']
['what', 'payment', 'methods', 'do', 'you', 'accept']
['payment', 'method', 'accept']
['how', 'do', 'i', 'reset', 'my', 'account', 'password']
['reset', 'account', 'password']
['is', 'there', 'a', 'warranty', 'on', 'electronic', 'items']
['warranty', 'electronic', 'item']
['how', 'long', 'does', 'delivery', 'take']
['long', 'delivery', 'take']
['can', 'i', 'change', 'my', 'shipping', 'address', 'after', 'placing', 'an', 'order']
['change', 'shipping', 'address', 'placing', 'order']
['do', 'you', 'have', 'a', 'physical', 'store', 'i', 'can', 'visit']
['physical', 'store', 'visit']
['how', 'do', 'i', 'apply', 'a', 'discount', 'code']
['apply', 'discount', 'code']
['what', 'should', 'i', 'do', 'if', 'my', 'item', 'arrived', 'damaged']
['item', 'arrived', 'damaged']
['are', 'there', 'any', 'membership', 'or', 'loyalty', 'programs']
['membership', 'loyalty', 'program']
['how', 'do', 'i', 'delete', 'my', 'account']
['delete', 'account']
--- Processed Dataframe ---

,Question,Answer,Cleaned_Question
0,How can I track my order?,You can track your order using the 'Track Orde...,track order
1,What is your return policy?,We offer a 30-day return policy for most items...,return policy
2,How do I cancel my order?,You can cancel your order from the 'My Orders'...,cancel order
3,Do you offer international shipping?,"Yes, we ship to over 50 countries. Shipping co...",offer international shipping
4,How can I contact customer support?,You can reach us via live chat on our website ...,contact customer support
5,What payment methods do you accept?,"We accept Visa, Mastercard, American Express, ...",payment method accept
6,How do I reset my account password?,"Go to the login page, click 'Forgot Password',...",reset account password
7,Is there a warranty on electronic items?,All electronics come with a standard 1-year ma...,warranty electronic item
8,How long does delivery take?,Standard delivery typically takes 3-5 business...,long delivery take
9,Can I change my shipping address after placing...,Shipping addresses can only be changed within ...,change shipping address placing order
10,Do you have a physical store I can visit?,We are an online-only store and do not have ph...,physical store visit
11,How do I apply a discount code?,You can enter your discount code in the 'Promo...,apply discount code
12,What should I do if my item arrived damaged?,Please take a photo of the damaged item and co...,item arrived damaged
13,Are there any membership or loyalty programs?,Yes! Our 'Rewards Club' allows you to earn poi...,membership loyalty program
14,How do I delete my account?,"To delete your account, please go to Account S...",delete account

In [15]:
type((faq["Question"]))
faq.iloc[9,1]

'Shipping addresses can only be changed within 1 hour of placing the order by contacting support immediately.'

#### Step 2: Vectorization (TF-IDF) Mathematical Phase

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')
cv_matrix = cv.fit_transform(faq['Cleaned_Question'])
cv.get_feature_names_out()

array(['accept', 'account', 'address', 'apply', 'arrived', 'cancel',
       'change', 'code', 'contact', 'customer', 'damaged', 'delete',
       'delivery', 'discount', 'electronic', 'international', 'item',
       'long', 'loyalty', 'membership', 'method', 'offer', 'order',
       'password', 'payment', 'physical', 'placing', 'policy', 'program',
       'reset', 'return', 'shipping', 'store', 'support', 'track',
       'visit', 'warranty'], dtype=object)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tf_matrix = tf.fit_transform(faq['Cleaned_Question'])
# tf_matrix.toarray()
print(tf_matrix.toarray()[:1])
print(tf.get_feature_names_out())
print(tf_matrix.shape)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.61252791 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.79044896
  0.         0.        ]]
['accept' 'account' 'address' 'apply' 'arrived' 'cancel' 'change' 'code'
 'contact' 'customer' 'damaged' 'delete' 'delivery' 'discount'
 'electronic' 'international' 'item' 'long' 'loyalty' 'membership'
 'method' 'offer' 'order' 'password' 'payment' 'physical' 'placing'
 'policy' 'program' 'reset' 'return' 'shipping' 'store' 'support' 'take'
 'track' 'visit' 'warranty']
(15, 38)

## Step 3: The "Chat" Logic (Cosine Similarity)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

def get_chatbot_response(user_input):
    # 1. Preprocess the user's question
    cleaned_input = preprocess_text(user_input)
    
    # 2. Transform input to vector (using the SAME vectorizer)
    user_vector = tf.transform([cleaned_input])
    
    # 3. Calculate similarity between user input and all FAQ questions
    # This returns an array of scores between 0 and 1
    similarities = cosine_similarity(user_vector, tf_matrix)
    print("similarity",similarities)
    # 4. Find the index of the highest score
    best_match_index = similarities.argmax()
    max_similarity = similarities[0][best_match_index]
    
    # 5. Set a threshold (if score is too low, the bot didn't understand)
    if max_similarity > 0.2:
        return faq['Answer'].iloc[best_match_index]
    else:
        return "I'm sorry, I don't understand that question. Could you try rephrasing?"

# --- TEST THE CHATBOT ---
print("\n--- Chatbot Test ---")
user_q = "i want to remove my account?"
print(f"User Asked: {user_q}")

--- Chatbot Test ---
User Asked: i want to remove my account?

In [23]:
answer = get_chatbot_response(user_q)
print(answer)

['i', 'want', 'to', 'remove', 'my', 'account']
['want', 'remove', 'account']
similarity [[0.         0.         0.         0.         0.         0.
  0.52324328 0.         0.         0.         0.         0.
  0.         0.         0.65564815]]
To delete your account, please go to Account Settings > Privacy or contact our data privacy team.

In [20]:
print("\n--- FAQ Chatbot is Online (Type 'quit' to exit) ---")

while True:
    user_input = input("You: ")
    
    if user_input.lower() in ['quit', 'exit', 'bye']:
        print("Bot: Goodbye! Have a great day.")
        break
        
    # Process input
    cleaned_input = preprocess_text(user_input)
    user_vector = tf.transform([cleaned_input])
    
    # Calculate Similarity
    similarities = cosine_similarity(user_vector, tf_matrix)
    best_match_index = similarities.argmax()
    confidence = similarities[0][best_match_index]
    
    # Logic for responses
    if confidence > 0.3:  # Adjusted threshold for better precision
        answer = faq['Answer'].iloc[best_match_index]
        print(f"Bot: {answer} (Confidence: {confidence:.2f})")
    else:
        print(f"Bot: I'm not quite sure about that. Can you try asking about shipping, returns, or payments? (Confidence: {confidence:.2f})")

--- FAQ Chatbot is Online (Type 'quit' to exit) ---
['hi']
['hi']
Bot: I'm not quite sure about that. Can you try asking about shipping, returns, or payments? (Confidence: 0.00)
Bot: Goodbye! Have a great day.